export const types = {
    CREATE_TASK: 'CREATE_TASK',
    REMOVE_TASK: 'REMOVE_TASK',
    FETCH_TASKS: 'FETCH_TASKS',
    FILL_TASKS: 'FILL_TASKS',
    UPDATE_TASK: 'UPDATE_TASK',
    EDITING_TASK: 'EDITING_TASK',

    CREATE_TASK_ASYNC: 'CREATE_TASK_ASYNC',
    REMOVE_TASK_ASYNC: 'REMOVE_TASK_ASYNC',
    REMOVE_TASK_ASYNC: 'REMOVE_TASK_ASYNC',
    UPDATE_TASK_ASYNC: 'UPDATE_TASK_ASYNC',
};